services:
  doorcontroller:
    image: door_controller:latest
    container_name: doorcontroller
    restart: unless-stopped
    volumes:
      - /opt/data/door_controller/data:/app/data
      - /opt/data/door_controller/config:/app/config
      - /opt/data/door_controller/log:/app/log

