services:
  keymanagement:
    #image: key-management-app:latest
    image: ghcr.io/ebpowell/BeSeenDoorController/key-management-app:latest
    container_name: keymanagement
    restart: unless-stopped
    volumes:
      - /opt/data/door_controller/data:/app/data
      - /opt/data/door_controller/config:/app/config
      - /opt/data/door_controller/log:/app/log

    environment:
      # Tell your app where to find config files
      APP_CONFIG_DIR: /app/config
      # APP_MODE: production

    # Set the user to run processes inside the container
    user: doorcontroller

    ports:
      - "5000:5000"
    command: ["BeSeen_web"]

    depends_on:
      - postgres

  doorcontroller:
    #image: cli-synch-tools:latest
    image: ghcr.io/ebpowell/BeSeenDoorController/cli-synch-tools:latest
    container_name: cli-synch-tools
    restart: unless-stopped
    volumes:
      - /opt/data/door_controller/data:/app/data
      - /opt/data/door_controller/config:/app/config
      - /opt/data/door_controller/log:/app/log

    environment:
      # Tell your app where to find config files
      APP_CONFIG_DIR: /app/config
      # APP_MODE: production

    # Set the user to run processes inside the container
    user: doorcontroller

    # Run get_swipes command on startup
    command: ["get_swipes"]
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /mnt/sda1/postgresql:/var/lib/postgresql/data
#      - /opt/postgresql:/var/lib/postgresql
#      - ./init:/docker-entrypoint-initdb.d/
    environment:
      - POSTGRES_PASSWORD=ww_s3cret
      - POSTGRES_USER=wentworth_user
      - POSTGRES_DB=wntworth_db
