services:
  beseen-api:
    build:
      context: .
      dockerfile: Dockerfile.beseen-api
    image: beseen-api:latest
    #image: ghcr.io/ebpowell/beseendoorcontroller/beseen-api:latest
    container_name: beseen-api
    restart: unless-stopped
    volumes:
      - /opt/data/door_controller/data:/app/data
      - /opt/data/door_controller/config:/app/config
      - /opt/data/door_controller/log:/app/log
      - /etc/localtime:/etc/localtime:ro

    environment:
      APP_CONFIG_DIR: /app/config
      TZ: America/New_York

    user: doorcontroller
    ports:
      - "5000:5000"

    # REST API server controlling calls to hardware controller (independent of PostgreSQL)
    command: ["BeSeen_api", "--host", "0.0.0.0", "--port", "5000"]

  config-gui:
    build:
      context: .
      dockerfile: Dockerfile.beseen-api
    image: beseen-api:latest
    #image: ghcr.io/ebpowell/beseendoorcontroller/beseen-api:latest
    container_name: config-gui
    restart: unless-stopped
    volumes:
      - /opt/data/door_controller/data:/app/data
      - /opt/data/door_controller/config:/app/config
      - /opt/data/door_controller/log:/app/log
      - /etc/localtime:/etc/localtime:ro

    environment:
      APP_CONFIG_DIR: /app/config
      API_URL: http://beseen-api:5000
      TZ: America/New_York

    user: doorcontroller
    ports:
      - "5001:5001"

    # Web GUI configuration management client
    command: ["BeSeen_config_gui", "--host", "0.0.0.0", "--port", "5001"]
    depends_on:
      - beseen-api

  cli-synch-tools:
    build:
      context: .
      dockerfile: Dockerfile.beseen-cli
    image: beseen-cli:latest
    #image: ghcr.io/ebpowell/beseendoorcontroller/beseen-cli:latest
    container_name: cli-synch-tools
    restart: unless-stopped
    volumes:
      - /opt/data/door_controller/data:/app/data
      - /opt/data/door_controller/config:/app/config
      - /opt/data/door_controller/log:/app/log
      - /etc/localtime:/etc/localtime:ro

    environment:
      APP_CONFIG_DIR: /app/config
      API_URL: http://beseen-api:5000
      TZ: America/New_York

    user: doorcontroller

    # Database synchronization tools daemon (associated with Postgres and dependent on API container)
    command: ["get_swipes"]
    depends_on:
      - beseen-api
      - postgres

  postgres:
    image: ghcr.io/ebpowell/beseendoorcontroller/postgres:sha-1412556
    build:
      context: .
      dockerfile: Dockerfile.postgres
    container_name: postgres
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - /mnt/sda1/postgresql:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d/
      - /etc/localtime:/etc/localtime:ro
      - /opt/data/door_controller/config:/app/config

    environment:
      - TZ=America/New_York
      - PGTZ=America/New_York
      - APP_CONFIG_DIR=/app/config
      - POSTGRES_PASSWORD=ww_s3cret
      - POSTGRES_USER=wentworth_user
      - POSTGRES_DB=wntworth_db
