app_name: Door Controller
settings:
  log_level: INFO
  urls:
    - http://69.21.119.147
  username: abc
  password: 654321
  recovery_delay: 5
  postgres_connect_string: postgresql://wentworth_user:password@localhost:5432/wntworth_db

ssl:
  enabled: false
  cert_file: config/certs/server.crt
  key_file: config/certs/server.key
