app_name: Door_Controller
settings:
  log_level: INFO
  urls:
    - http://69.21.119.147
    - http://69.21.119.148
  username: abc
  password: 654321
  recovery_delay: 5
  iterations: 25
  postgres_connect_string: postgresql://wentworth_user:ww_s3cret@bigdata:5432/wntworth_db
  api_server:
    host: 192.168.1.250
    port: 5000

ssl:
  enabled: false
  cert_file: config/certs/server.crt
  key_file: config/certs/server.key
